version: '3'

services:
  xhsdb:
    container_name: xhsdb
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
      MYSQL_DATABASE: xiaohongshu # for database creation automatically

    # 端口映射
    ports:
      - 3306:3306
    # 数据挂载
    volumes:
      - "./data:/var/lib/mysql"