// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-bbs-demo/internal/biz"
	"kratos-bbs-demo/internal/conf"
	"kratos-bbs-demo/internal/data"
	"kratos-bbs-demo/internal/server"
	"kratos-bbs-demo/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	profileRepo := data.NewProfileRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, profileRepo, logger)
	xiaohongshuService := service.NewXiaohongshuService(userUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, xiaohongshuService, logger)
	httpServer := server.NewHTTPServer(confServer, xiaohongshuService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
